([zk_145_ubistvo_na_mah] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_145_ubistvo_na_mah)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_145_ubistvo_na_mah)
   (rules [rule2] [rule1])
   (defeasible-stratum 0))

([zk_153_ucestvovanje_u_tuci] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_153_ucestvovanje_u_tuci)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_153_ucestvovanje_u_tuci)
   (rules [rule4] [rule3])
   (defeasible-stratum 0))

([zk_154_ugrozavanjem_opasnim_orudjem_pri_tuci_i_svadji] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_154_ugrozavanjem_opasnim_orudjem_pri_tuci_i_svadji)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_154_ugrozavanjem_opasnim_orudjem_pri_tuci_i_svadji)
   (rules [rule6] [rule5])
   (defeasible-stratum 0))

([zk_152_laka_tjelesna_povreda] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_laka_tjelesna_povreda)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_152_laka_tjelesna_povreda)
   (rules [rule8] [rule7])
   (defeasible-stratum 0))

([zk_152_laka_tjelesna_povreda_sa_oruzjem_orudjem] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_laka_tjelesna_povreda_sa_oruzjem_orudjem)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_152_laka_tjelesna_povreda_sa_oruzjem_orudjem)
   (rules [rule10] [rule9])
   (defeasible-stratum 0))

([zk_152_opomena_laka_tjelesna_povreda_sa_oruzjem_orudjem] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_opomena_laka_tjelesna_povreda_sa_oruzjem_orudjem)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_152_opomena_laka_tjelesna_povreda_sa_oruzjem_orudjem)
   (rules [rule11])
   (defeasible-stratum 0))

([zk_152_laka_tjelesna_povreda_gonjenje_po_privatnoj_tuzbi] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_laka_tjelesna_povreda_gonjenje_po_privatnoj_tuzbi)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_152_laka_tjelesna_povreda_gonjenje_po_privatnoj_tuzbi)
   (rules [rule12])
   (defeasible-stratum 0))

([zk_151_teska_tjelesna_povreda] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_tjelesna_povreda)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151_teska_tjelesna_povreda)
   (rules [rule14] [rule13])
   (defeasible-stratum 0))

([zk_151_teska_tjelesna_povreda_naneta_teska_doveden_zivot_u_opasnost_ili_naneta_trajna_nesposobnost] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_tjelesna_povreda_naneta_teska_doveden_zivot_u_opasnost_ili_naneta_trajna_nesposobnost)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151_teska_tjelesna_povreda_naneta_teska_doveden_zivot_u_opasnost_ili_naneta_trajna_nesposobnost)
   (rules [rule16] [rule15])
   (defeasible-stratum 0))

([zk_151_teska_tjelesna_povreda_i_nastupila_smrt] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_tjelesna_povreda_i_nastupila_smrt)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151_teska_tjelesna_povreda_i_nastupila_smrt)
   (rules [rule17])
   (defeasible-stratum 0))

([zk_151_teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151_teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (rules [rule18])
   (defeasible-stratum 0))

([zk_151_tesko_telesno_povrijedi_ili_mu_zdravlje_narusi_ucinjeno_na_mah_doveden_u_razdrazenost_bez_svoje_krivice] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_tesko_telesno_povrijedi_ili_mu_zdravlje_narusi_ucinjeno_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151_tesko_telesno_povrijedi_ili_mu_zdravlje_narusi_ucinjeno_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (rules [rule19])
   (defeasible-stratum 0))

([zk_151_teska_telesna_povreda_ili_zdravlje_tesko_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_na_mah_doveden_u_razdrazenost_bez_svoje_krivice] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_telesna_povreda_ili_zdravlje_tesko_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151_teska_telesna_povreda_ili_zdravlje_tesko_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (rules [rule20])
   (defeasible-stratum 0))

([zk_151_teska_telesna_povreda_i_nastupila_smrt_doveden_u_razdrazenost_bez_svoje_krivice] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_telesna_povreda_i_nastupila_smrt_doveden_u_razdrazenost_bez_svoje_krivice)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151_teska_telesna_povreda_i_nastupila_smrt_doveden_u_razdrazenost_bez_svoje_krivice)
   (rules [rule21])
   (defeasible-stratum 0))

([zk_151a_sakacenje_zenskih_genitalija] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151a_sakacenje_zenskih_genitalija)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151a_sakacenje_zenskih_genitalija)
   (rules [rule22])
   (defeasible-stratum 0))

([zk_151b_prinudna_sterilizacija] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151b_prinudna_sterilizacija)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name zk_151b_prinudna_sterilizacija)
   (rules [rule23])
   (defeasible-stratum 0))

([min_years_in_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_years_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name min_years_in_imprisonment)
   (rules [pen24] [pen16] [pen14] [pen4] [pen1])
   (defeasible-stratum 0))

([max_years_in_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_years_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name max_years_in_imprisonment)
   (rules [pen27] [pen25] [pen23] [pen21] [pen19] [pen18] [pen17] [pen15] [pen13] [pen9] [pen2])
   (defeasible-stratum 0))

([min_months_in_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_months_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name min_months_in_imprisonment)
   (rules [pen26] [pen22] [pen20] [pen12] [pen3])
   (defeasible-stratum 0))

([novcana_kazna] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label novcana_kazna)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name novcana_kazna)
   (rules [pen7] [pen5])
   (defeasible-stratum 0))

([months_in_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label months_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name months_in_imprisonment)
   (rules [pen6])
   (defeasible-stratum 0))

([years_in_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label years_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name years_in_imprisonment)
   (rules [pen8])
   (defeasible-stratum 0))

([izrecena_opomena] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label izrecena_opomena)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name izrecena_opomena)
   (rules [pen10])
   (defeasible-stratum 0))

([gonjenje_po_privatnoj_tuzbi] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label gonjenje_po_privatnoj_tuzbi)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name gonjenje_po_privatnoj_tuzbi)
   (rules [pen11])
   (defeasible-stratum 0))

