([zk_145_ubistvo_na_mah-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_145_ubistvo_na_mah)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule2-deductive-gen499] [rule1-deductive-gen498]))

([zk_153_ucestvovanje_u_tuci-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_153_ucestvovanje_u_tuci)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule4-deductive-gen501] [rule3-deductive-gen500]))

([zk_154_ugrozavanjem_opasnim_orudjem_pri_tuci_i_svadji-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_154_ugrozavanjem_opasnim_orudjem_pri_tuci_i_svadji)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule6-deductive-gen503] [rule5-deductive-gen502]))

([zk_152_laka_tjelesna_povreda-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_laka_tjelesna_povreda)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule8-deductive-gen505] [rule7-deductive-gen504]))

([zk_152_laka_tjelesna_povreda_sa_oruzjem_orudjem-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_laka_tjelesna_povreda_sa_oruzjem_orudjem)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule10-deductive-gen507] [rule9-deductive-gen506]))

([zk_152_opomena_laka_tjelesna_povreda_sa_oruzjem_orudjem-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_opomena_laka_tjelesna_povreda_sa_oruzjem_orudjem)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule11-deductive-gen508]))

([zk_152_laka_tjelesna_povreda_gonjenje_po_privatnoj_tuzbi-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_152_laka_tjelesna_povreda_gonjenje_po_privatnoj_tuzbi)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule12-deductive-gen509]))

([zk_151_teska_tjelesna_povreda-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_tjelesna_povreda)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule14-deductive-gen511] [rule13-deductive-gen510]))

([zk_151_teska_tjelesna_povreda_naneta_teska_doveden_zivot_u_opasnost_ili_naneta_trajna_nesposobnost-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_tjelesna_povreda_naneta_teska_doveden_zivot_u_opasnost_ili_naneta_trajna_nesposobnost)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule16-deductive-gen513] [rule15-deductive-gen512]))

([zk_151_teska_tjelesna_povreda_i_nastupila_smrt-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_tjelesna_povreda_i_nastupila_smrt)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule17-deductive-gen514]))

([zk_151_teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule18-deductive-gen515]))

([zk_151_tesko_telesno_povrijedi_ili_mu_zdravlje_narusi_ucinjeno_na_mah_doveden_u_razdrazenost_bez_svoje_krivice-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_tesko_telesno_povrijedi_ili_mu_zdravlje_narusi_ucinjeno_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule19-deductive-gen516]))

([zk_151_teska_telesna_povreda_ili_zdravlje_tesko_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_na_mah_doveden_u_razdrazenost_bez_svoje_krivice-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_telesna_povreda_ili_zdravlje_tesko_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule20-deductive-gen517]))

([zk_151_teska_telesna_povreda_i_nastupila_smrt_doveden_u_razdrazenost_bez_svoje_krivice-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151_teska_telesna_povreda_i_nastupila_smrt_doveden_u_razdrazenost_bez_svoje_krivice)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule21-deductive-gen518]))

([zk_151a_sakacenje_zenskih_genitalija-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151a_sakacenje_zenskih_genitalija)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule22-deductive-gen519]))

([zk_151b_prinudna_sterilizacija-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label zk_151b_prinudna_sterilizacija)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule23-deductive-gen520]))

([min_years_in_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_years_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen24-deductive-gen544] [pen16-deductive-gen536] [pen14-deductive-gen534] [pen4-deductive-gen524] [pen1-deductive-gen521]))

([max_years_in_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_years_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen27-deductive-gen547] [pen25-deductive-gen545] [pen23-deductive-gen543] [pen21-deductive-gen541] [pen19-deductive-gen539] [pen18-deductive-gen538] [pen17-deductive-gen537] [pen15-deductive-gen535] [pen13-deductive-gen533] [pen9-deductive-gen529] [pen2-deductive-gen522]))

([min_months_in_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_months_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen26-deductive-gen546] [pen22-deductive-gen542] [pen20-deductive-gen540] [pen12-deductive-gen532] [pen3-deductive-gen523]))

([novcana_kazna-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label novcana_kazna)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen7-deductive-gen527] [pen5-deductive-gen525]))

([months_in_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label months_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen6-deductive-gen526]))

([years_in_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label years_in_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen8-deductive-gen528]))

([izrecena_opomena-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label izrecena_opomena)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen10-deductive-gen530]))

([gonjenje_po_privatnoj_tuzbi-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:prinudna_sterilizacija)
   (lc:sakacenje_zenskih_genitalija)
   (lc:ucini_na_mah_doveden_u_razdrazenost_bez_svoje_krivice)
   (lc:teska_telesna_povreda_ili_zdravlje_narusi_iz_nehata)
   (lc:teska_telesna_povreda_i_nastupila_smrt)
   (lc:tesko_telesno_povredi_ili_mu_zdravlje_narusi_tako_da_mu_je_doveden_zivot_u_opasnost_ili_unisten_ili_ostecen_trajno_deo_tela_naneta_trajna_nesposonost)
   (lc:tesko_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:gonjenje_se_preduzima_po_privatnoj_tuzbi)
   (lc:ucinilac_bio_izazvan_nepristojnim_ili_grubim_ponasanjem_ostecenog)
   (lc:oruzjem_orudjem_lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:lako_telesno_povrijedi_ili_mu_zdravlje_narusi)
   (lc:pri_svadji_se_masi_oruzja_podobnog_da_tijelo_tesko_povredi)
   (lc:ubistvo_na_mah)
   (lc:neko_lisen_zivota_ili_nanesena_teska_telesna_povreda)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label gonjenje_po_privatnoj_tuzbi)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen11-deductive-gen531]))

